  services:
    mariadb: 
      build: 
        context: requirements/mariadb
        args:
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_ADMIN_USER=${MARIADB_ADMIN_USER}
            - MARIADB_ADMIN_PASSWORD=${MARIADB_ADMIN_PASSWORD}
      image: mariadb
      container_name: mariadb
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        dockern:
          ipv4_address: 10.0.0.2
      environment:
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      restart: on-failure
    nginx:
      build: requirements/nginx
      image: nginx
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - wordpress:/usr/share/wordpress
      depends_on:
        -  "mariadb"
      networks:
        dockern:
          ipv4_address: 10.0.0.3
      restart: on-failure
    wordpress:
      build: 
        context: requirements/wordpress
      image: wordpress
      container_name: wordpress
      volumes:
        - wordpress:/usr/share/wordpress
      networks:
        dockern:
          ipv4_address: 10.0.0.4
      restart: on-failure
      environment:
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - HOST_NAME=${HOST_NAME}
        - HTTP_HOST=${HOST_NAME}
        - WP_USER=${WP_USER}
        - WP_PASSWORD=${WP_PASSWORD}
        - WP_EMAIL=${WP_EMAIL}
        - NEW_WP_USER=${NEW_WP_USER}
        - NEW_WP_PASSWORD=${NEW_WP_PASSWORD}
        - NEW_WP_EMAIL=${NEW_WP_EMAIL}
      depends_on:
        - mariadb
  volumes:
    mariadb:
      {} 
    wordpress:
      {} 
  networks:
    dockern:
      name: dockern 
      ipam:
        config:
          - subnet: 10.0.0.0/29
            gateway: 10.0.0.1

    
